server.port             = 80
server.username         = "lighttpd"
server.groupname        = "lighttpd"
server.document-root    = "/usr/share/webapps/cgit/"

server.modules += (
    "mod_redirect",
    "mod_cgi",
    "mod_rewrite"
)

mimetype.assign = (
    ".css" => "text/css",
    ".js"  => "application/javascript",
    ".png" => "image/png",
    ".ico" => "image/x-icon",
    ".txt" => "text/plain"
)

$HTTP["url"] =~ "^/cgit\.cgi" {
    cgi.assign = ( "cgit.cgi" => "" )
}

url.redirect = (
    "^/git/(.*)$" => "/cgit.cgi/$1",
)

url.rewrite-once = (
    "^/(.*)$" => "/cgit.cgi/$1"
)
