networks:
  forgejo:

services:
  forgejo-db:
    container_name: forgejo-db
    image: postgres:18-alpine
    restart: unless-stopped
    networks:
      - forgejo
    volumes:
      - ./db.vol:/var/lib/postgresql/data
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 60M

  forgejo-init:
    container_name: forgejo-init
    image: alpine:3.23
    networks:
      - forgejo
    volumes:
      - ./data.vol:/data
    user: root
    command: chown -R 1000:1000 /data

  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:15
    restart: unless-stopped
    depends_on:
      forgejo-db:
        condition: service_started
      forgejo-init:
        condition: service_completed_successfully
      cloudflare-tunnel:
        condition: service_started
      tailscale:
        condition: service_started
    networks:
      - forgejo
      - cloudflare
    ports:
      - 222:22
    volumes:
      - ./data.vol:/data
      - ./public:/data/gitea/public
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: ".env"
    environment:
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: forgejo-db:5432
      FORGEJO__server__SSH_LISTEN_HOST: 0.0.0.0
      FORGEJO__server__SSH_LISTEN_PORT: 22
      FORGEJO__server__SSH_PORT: 222
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 200M
