services:
  samba:
    container_name: samba
    image: dockurr/samba
    restart: unless-stopped
    ports:
      - 5212:445
    volumes:
      - ./data.vol:/storage
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 100M
