services:
  omnisearch:
    container_name: omnisearch
    build: ./source.vol
    restart: unless-stopped
    depends_on:
      - cloudflare-tunnel
    networks:
      - cloudflare
    volumes:
      - ./source.vol/locales:/app/locales:ro
      - ./config.ini:/etc/omnisearch/config.ini:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 20M
          cpus: "0.86"
